### ISSUE TITLE
I barely know how to code, can someone explain how to add an image to the timeline?

### ISSUE THREAD

**Issue by nimrodeilon** [seanlowe/obsidian-timelines#106]
i managed to setup a timeline and add events but when i try to add an image i get a black rectangle. i'm probably doing something wrong with the path so i pasted here the code

![image](https://github.com/user-attachments/assets/5da269cc-8fe0-4391-9370-da11fcaab829)
![image](https://github.com/user-attachments/assets/f731066a-50f7-4186-84ed-f5bd47622f1c)

**Comment by seanlowe** [comment]
Hi, the image functionality only works if the image is stored in the vault and the absolute path described in the docs refers to the absolute path starting from the top level directory of the vault IIRC.

Let me know if you try both of those things and it still doesn't work.

**Comment by nimrodeilon** [comment]
thanks for the answer, sorry for the ignorance but how can i check the path?

**Comment by seanlowe** [comment]
No worries! I had to look it up myself because it's been a while, lol.

Here's an example vault, laid out like so:
```
files/
 -> notes/
   -> some_note_with_events.md
   -> event_picture.png
 -> timeline.md
attachments/
 -> picture_1.png
 -> picture_2.png
some_file_on_top_level.md
some_picture_on_top_level.png
```

If you wanted to add an image to `some_note_with_events.md`, we can see we have 3 different places we can get them from the top level directory, some pictures under the `attachments/` directory, and then there's a picture in `files/notes/`

the `data-img` tag on your event for each of those places would look like so:
```
// for some_picture_on_top_level.png
data-img="some_picture_on_top_level.png"

// for attachments/picture_1.png
data-img="attachments/picture_1.png"

// for files/notes/event_picture.png
data-img="files/notes/event_picture.png"
```

The `data-img` tag takes an "absolute local path", meaning that your path starts at the beginning of your vault and follows it from there.

Let me know if there are any problems after trying it this way!

---

P.S. I used `/` in my path because I use Linux. I tested it with `\` and it still works so it shouldn't matter how you format your path
