### ISSUE TITLE
[Bug - Vertical] collapsing an event that is not a time range changes date to "undefined"

### ISSUE THREAD

**Issue by seanlowe** [seanlowe/obsidian-timelines#67]
expanded:
![image](https://github.com/seanlowe/obsidian-timelines/assets/35589586/b4302813-4cad-43c9-8581-abc3e4d67b61)

collapsed:
![image](https://github.com/seanlowe/obsidian-timelines/assets/35589586/6d1866b5-5acd-41e8-9b48-e6e021dae959)

**Comment by QuantumBob** [comment]
in file vertical.ts on line 115.
Instead of

noteHdrs[0].setText( collapsed ? datedTo[1] : datedTo[0] )

relplace with

if (datedTo[1] === undefined){
   noteHdrs[0].setText(datedTo[0]);
}else {
   noteHdrs[0].setText(collapsed ? datedTo[1] : datedTo[0]);
}

Sorry not a git person so this is the only way to edit code...

Thanks, great plugin btw
