### ISSUE TITLE
有没有教程

### ISSUE THREAD

**Issue by barye81** [seanlowe/obsidian-timelines#79]
有没有教程，没试出来

**Comment by seanlowe** [comment]
Assuming google translate is correct, there is no **video** tutorial but the [docs](https://seanlowe.github.io/obsidian-timelines/docs/) have plenty of information to get you started. Be sure to give it a look.

In the future, please make any issues in English unless possible mistranslation from google translate is acceptable.

I'm closing this issue since it's not really a bug.
