### ISSUE TITLE
Not showing correctly

### ISSUE THREAD

**Issue by DM-Homebrew** [seanlowe/obsidian-timelines#83]
Got the events showing but it is all displaying weird. and the data-color won't change the color, weird horizontal rules, the overlap of the timeline doesnt match the start and end dates, etc.
![ob-timeline](https://github.com/user-attachments/assets/614bcb25-90d1-4a65-93d2-bb4737d08dd3)
![ob-timeline](https://github.com/user-attachments/assets/05e0103c-5a97-4f4d-b294-7575a5150c23)

**Comment by seanlowe** [comment]
Yeah that is some messy stuff. Let's make a list of items here that are actionable for me to fix:
- [ ] no space between end dates and era indicator
- [ ] data-color does not affect vertical timeline colors of ranges / events (I think this will actually be a new feature)
- [ ]  timeline order is incorrect. first event should (realistically) have no overlap with second event

Question, are you using a theme with your obsidian vault? I'd be interested to know what theme so that I could test with it and make sure there's nothing in my plugin that uses overly common class names or things that don't mesh well with a theme.

You mention horizontal rules. What problems did you run into with the horizontal rules, perhaps I can shed some light on them?

**Comment by DM-Homebrew** [comment]
I do have a theme, I also have more plug-ins. Give me a few and I am going to duplicate the file and start turning stuff off one buy one and see if there is a change and let you know what is particularly messing it up if any.

**Comment by seanlowe** [comment]
> * [x]  no space between end dates and era indicator
> * [ ]  data-color does not affect vertical timeline colors of ranges / events (I think this will actually be a new feature)
> * [x]   timeline order is incorrect. first event should (realistically) have no overlap with second event

Hey, these two items should be fixed in release 2.2.7. If you have any further questions or run into any issues, please create a new github issue. I'm going to make a new issue for the colors thing for vertical timelines.

Thanks for creating the issue! Hope this helps.
