### ISSUE TITLE
[Feature - Vertical] Allow custom date formatting

### ISSUE THREAD

**Issue by weirdwizardthomas** [seanlowe/obsidian-timelines#87]
For display purposes, it'd be neat we could provide our own formatting string to display in the timeline.

**Comment by seanlowe** [comment]
Hey, could you elaborate on what kind of formatting you'd like to do / how you'd like this to work?

This should be possible. I would just need to have a well-defined end goal. 😃

**Comment by profxavr** [comment]
For the date display, it would be nice to have an option in the options to say "Display Format" and you get to specify "MM/DD/YYYY" or "YYYY-MM-DD" or whatever other options. 

I would like this feature because I don't want to display the hour by default, and I think the dates on the timeline would be "prettier" with the months potentially written out.

**Comment by StanislasSiweck** [comment]
I agree with you, I just use the years (horizontal/vertical) and having the MM-DD is not the most beautiful, a “Display” option could be nice to display our date we want in the timeline (January 1st for example).

**Comment by seanlowe** [comment]
I'm thinking of implementing two separate options here. One that goes into the codeblock, something like:
````
```ob-timeline
tags=history;rule
dateFormat="MM/DD/YYYY"
```
````

or 

````
```ob-timeline
tags=history;rule
dateFormat="D M, 'YY"
```
````

something that allows a user to set an *override* to a particular timeline rather than setting it universally.

But then in the actual settings of the plugin I want to have a "Default Date Format" which would apply universally. I'd likely default that to the current YYYY-MM-DD-HH.

Thoughts?
