### ISSUE TITLE
data-type works unstable

### ISSUE THREAD

**Issue by OvenVan** [seanlowe/obsidian-timelines#93]
Hey! Thank you for your effort in this.

However, I found something strange when I am using this plugin. The data-type parameter works really strange, as I will show below:

Situation A:
<div class="ob-timelines"
	data-title="event"
	data-start-date="200"
	data-end-date="300"
	data-era="BCE"
	data-type="range">	
	This is an event
</div>
and I get this, which is quite good
<img width="407" alt="image" src="https://github.com/user-attachments/assets/bb857038-d070-4153-9588-ccf1f05531ca">

However, when I change the start-date into "200-00-00-00" and end-date to "300-00-00-00", the range option seems not working:
<img width="299" alt="image" src="https://github.com/user-attachments/assets/d60c5151-7bd0-44de-bf06-16e8fd9a02c5">
<img width="392" alt="image" src="https://github.com/user-attachments/assets/da11f37b-3bc4-4568-b29c-5bcc0ad85c8d">

I don't know if there is anything I went wrong. If it does, please tell me, thank you!

**Comment by seanlowe** [comment]
Hey, took me a while to get back but the way I have written date parsing right now it breaks if you send in all 0's for month/day/hour sections. You can leave them out and it works. Or if you want a particular month you can do like 200-01 and leave off the rest and that should work also

there's another issue created that I haven't had time to work on recently where passing `200` or `200-1` or some such should display that, not `200-1-1-1`. #86 

I'm going to close this issue since it's technically not an issue. If you run into any more problems let me know! Thanks!
